' <auto-generated> This file has been auto generated. </auto-generated>
<Microsoft.VisualStudio.TestPlatform.TestSDKAutoGeneratedCode>
Friend Class AutoGeneratedProgram

    Shared Sub Main(ByVal args As String())
    End Sub
End Class
